---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: grsec, tags: ['grsec'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
    - { role: pass, tags: ['pass'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: networkmanager, tags: ['networkmanager'] }
#    - { role: macchiato, tags: ['macchiato'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: tor, tags: ['tor'], when: "tor is defined" }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: udisks, tags: ['udisks'] }
    - { role: spell, tags: ['spell'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: media, tags: ['media'] }
    - { role: mpd, tags: ['mpd'] }
    - { role: laptop, tags: ['laptop'] }
    - { role: weechat, tags: ['weechat'] }
    - { role: git-annex, tags: ['git-annex'], when: "gitannex is defined" }
    - { role: ledger, tags: ['ledger'] }
    - { role: mail, tags: ['mail'] }
    - { role: cups, tags: ['cups'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: hashicorp, tags: ['hashicorp'] }
#    - { role: virtualenv, tags: ['virtualenv'] }
    - { role: sound, tags: ['sound'] }
    - { role: pim, tags: ['pim'] }
#    - { role: postgresql, tags: ['postgresql'] }
    - { role: aws, tags: ['aws'] }
#    - { role: parcimonie, tags: ['parcimonie'], when: "tor is defined" }
    - { role: localtime, tags: ['localtime'], when: "localtime is defined" }
    - { role: bluetooth, tags: ['bluetooth'], when: "bluetooth is defined" }
    - { role: wttr, tags: ['wttr'] }
#    - { role: hostsctl, tags: ['hostsctl'], when: "hostsctl is defined" }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
