---
- name: Install calibre
  pacman: name=calibre state=present

- name: Jail calibre
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/calibre
        state=link
  tags:
    - firejail

- name: Push calibre firejail profile
  copy: src=firejail/calibre.profile dest=/usr/local/etc/firejail/calibre.profile
  notify:
    - activate firejail profiles
  tags:
    - firejail
